### ISSUE TITLE
Installing as Flatpak from Flathub

### ISSUE THREAD

**Issue by sojusnik** [sezanzeb/key-mapper#21]
Thanks for creating such an useful app!

Did you think about offering this app as a Flatpak on [Flathub](https://flathub.org/) to be easily installable and updatable?

**Comment by sezanzeb** [comment]
I don't have any experience with Flatpak, never used it.

I played around a little with `flatpak-builder --user --install build-dir key-mapper.yml` and

```
app-id: key-mapper
runtime: org.gnome.Platform
runtime-version: '3.38'
sdk: org.gnome.Sdk
rename-appdata-file: key-mapper.appdata.xml
rename-desktop-file: key-mapper.desktop
rename-icon: key-mapper
command: key-mapper
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
modules:
  - name: python-evdev
    buildsystem: simple
    build-commands:
      - python3 setup.py install --prefix=/app
    sources:
      - type: git
        url: https://github.com/gvalkov/python-evdev.git
  - name: key-mapper
    buildsystem: simple
    build-commands:
      - python3 setup.py install --root=/app
    sources:
      - type: git
        url: https://github.com/sezanzeb/key-mapper.git
        branch: main
```

But it fails, maybe somebody with experience can do this. pydbus and setuptools also needs to be added.
